### PR TITLE
Authenticate Fulfillment Service Requests

### LINKED ISSUE #578: Authentication for FulfillmentService callback requests
## Overview

I'm building an fulfillment service app based on the shopify-app-remix template. There doesn't seem to be a utility for validating incoming requests to the FulfillmentService `callback_url` like there is for e.g. webhooks. From the wording in [docs](https://shopify.dev/docs/apps/fulfillment/fulfillment-service-apps/manage-fulfillments#step-3-act-on-fulfillment-requests) I hoped `shopify.authenticate.webhook(request)` would work, but unfortunately it fails with an error.

### PR DESCRIPTION
**Pull request by lizkenyon**
### WHY are these changes introduced?

Fixes #578 

### WHAT is this pull request doing?
* Adds new API to authenticate fulfillment service notifications
* [For fulfillment management apps](https://shopify.dev/docs/apps/fulfillment/fulfillment-service-apps/manage-fulfillments)

#### To test
* Add a new route in your app to receive fulfillment notifications `<callback_url>/fulfillment_order_notification`
* Create a fulfillment service
```
mutation fulfilmentServiceCreate {
    fulfillmentServiceCreate(name: "my valid fulfillment service",
    fulfillmentOrdersOptIn: true,
    callbackUrl: "https://my-tunnel.trycloudflare.com",) {
      fulfillmentService {
        handle
        id
        callbackUrl
      }
    userErrors {
      field
      message
    }
    }
  }
```

* In Shopify Admin update the location of a product to the new fulfillment service
* Create a draft order with the product
* Click `Request fulfillment`
* Verify your server logs that requests are being authenticated

image

## Type of change

- [ ] Patch: Bug (non-breaking change which fixes an issue)
- [x] Minor: New feature (non-breaking change which adds functionality)
- [ ] Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have used `yarn changeset` to create a draft changelog entry (do NOT update the `CHANGELOG.md` files manually)
- [x] I have added/updated tests for this change
- [x] I have documented new APIs/updated the documentation for modified APIs (for public APIs)

### CODE REVIEW

File: packages/shopify-app-remix/src/server/authenticate/fulfillment-service/authenticate.ts [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+      });
+    }
+
+    logger.debug('Found a session for the fulfillment service request', {
+      shop,
+    });
+
+    return {
+      session,
+      kind: payload.kind,
```
Comment (paulomarg) [inline packages/shopify-app-remix/src/server/authenticate/fulfillment-service/authenticate.ts:78]: Is the payload just the kind, or will it contain other information? If it does, should we consider returning the whole thing?

File: packages/shopify-app-remix/src/server/authenticate/fulfillment-service/types.ts [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+  /**
+   * A session with an offline token for the shop.
+   *
+   * Returned only if there is a session for the shop.
+   * */
+  session: Session;
+  /**
+   * A session with an offline token for the shop.
+   *
+   * Returned only if there is a session for the shop.
```
Comment (paulomarg) [inline packages/shopify-app-remix/src/server/authenticate/fulfillment-service/types.ts:17]: Wrong description?

File: packages/shopify-app-remix/src/server/authenticate/fulfillment-service/types.ts [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+   * <caption>Fulfillment service request payload.</caption>
+   * <description>Get the request's POST payload.</description>
+   * ```ts
+   * /app/routes/fulfillment_order_notification.ts
+   * import { ActionFunction } from "@remix-run/node";
+   * import { authenticate } from "../shopify.server";
+   *
+   * export const action: ActionFunction = async ({ request }) => {
+   *   const { kind } = await authenticate.fulfillmentService(request);
+   *   console.log(kind);
```
Comment (paulomarg) [inline packages/shopify-app-remix/src/server/authenticate/fulfillment-service/types.ts:64]: Nit, but I think a more meaningful example would be to `switch` on the potential values `kind` can have?

File: packages/shopify-app-remix/src/server/authenticate/fulfillment-service/types.ts [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+   * import { authenticate } from "../shopify.server";
+   *
+   * export async function action({ request }: ActionFunctionArgs) {
+   *   const { admin } = await authenticate.fulfillmentService(request);
+   *
+   *   const response = await admin.graphql(
+   *     `#graphql
+   *     mutation acceptFulfillmentRequest {
+   *       fulfillmentOrderAcceptFulfillmentRequest(
+   *            id: "gid://shopify/FulfillmentOrder/5014440902678",
```
Comment (paulomarg) [inline packages/shopify-app-remix/src/server/authenticate/fulfillment-service/types.ts:34]: Just curiosity, where does the id come from in this scenario?

File: packages/shopify-app-remix/src/server/authenticate/fulfillment-service/authenticate.fulfillment-service.doc.ts
Comment (paulomarg) [inline packages/shopify-app-remix/src/server/authenticate/fulfillment-service/authenticate.fulfillment-service.doc.ts:1]: We also added a default example for the different authentication methods. We should do that for consistency here too.

**Review by paulomarg — COMMENTED** [review]
Looking really good! Just a question around the returned data, but otherwise everything is just nits.

File: packages/shopify-app-remix/src/server/authenticate/fulfillment-service/authenticate.ts (hunk 1 above)
Comment (lizkenyon) [reply packages/shopify-app-remix/src/server/authenticate/fulfillment-service/authenticate.ts:78]: It would future proof it but wouldn't we also loose type safety?

**Review by paulomarg — APPROVED** [review]

File: packages/shopify-app-remix/src/server/authenticate/fulfillment-service/types.ts [hunk 5]
```diff
@@ -97,21 +97,18 @@ export interface FulfillmentServiceContext<
...
+   *   } else if (payload.kind === 'CANCELLATION_REQUEST') {
    *    // handle cancellation request
    *   };
    * return new Response();
    * ```
    */
-  kind: FulfillmentServiceRequestKind;
-}
-
-export enum FulfillmentServiceRequestKind {
```
Comment (paulomarg) [inline packages/shopify-app-remix/src/server/authenticate/fulfillment-service/types.ts]: Good call removing the enum. It's nice but it would tie this code to the requests, which could make it harder for apps to implement this.

**Review by paulomarg — APPROVED** [review]
